const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{FUNDO: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{JOGADOR: 0},
	{Sólido: 0},
	{CHAO: 0},
	{Fixar: 0},
	{LUFFY: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Senóide: 0},
	{Sprite: 0},
	{Projétil: 0},
	{DarAVolta: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Âncora: 0},
	{Texto: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Texto2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Texto3: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Texto4: 0},
	{Sprite14: 0},
	{GEAR5: 0},
	{TEMPOGEAR5: 0},
	{TEMPO: 0},
	{PONTO: 0}
];

self.InstanceType = {
	FUNDO: class extends self.ITiledBackgroundInstance {},
	JOGADOR: class extends self.ISpriteInstance {},
	CHAO: class extends self.ISpriteInstance {},
	LUFFY: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}